# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the vendor drivers
#

obj-$(CONFIG_AMLOGIC_BATTERY)	+= battery/
obj-$(CONFIG_AMLOGIC_BLUETOOTH)	+= bluetooth/
obj-$(CONFIG_AMLOGIC_DRM_PANEL)	+= panel/
obj-$(CONFIG_RTL8822CS)	+= rtl88x2cs/
obj-y += wifi/
obj-y += media/
